Project/Moviesio/app/views.py
from flask import render_template_string ,render_template, Blueprint, jsonify, request, redirect, url_for
import os
import requests
import json
from ...Models import (Requests, serialize)


Moviesio = Blueprint('moviesio',
                     __name__,
                     template_folder='../templates')

# storing the api key somewhere
api_key = os.environ.get('TMDB_KEY')  # call it whatever you want

key_word = '?api_key='

# global tmdb (movie database) url
global_url = 'https://api.themoviedb.org/3/'

# language to use
language = '&language=en-US'
url_trend = 'trending/'
url_popular = 'popular'

# Will be  collecting every key value (specified) once this function is called


def extract_values(obj, key):
    # pull all vlaues of specific key from json data
    arr = []

    def extract(obj, arr, key):
        # search for value keys in json
        if isinstance(obj, dict):
            for k, v in obj.items():
                if isinstance(v, (dict, list)):
                    extract(v, arr, key)
                elif k == key:
                    arr.append(v)
        elif isinstance(obj, list):
            for item in obj:
                extract(item, arr, key)
        return arr

    results = extract(obj, arr, key)
    return results

# Trending view --> extend other views
@Moviesio.route('/', methods=['POST', 'GET'])
def get_trending():

    time_window = 'week'  # can be changed

    # switching to either (tv|movie) view
    if request.method == 'POST':
    
        # variable received from ajax call
        choice_clicked = request.form.get('choice_clicked', None)

        if choice_clicked == "tv" or choice_clicked == 'movie':
            media_type = choice_clicked + '/'
            print(media_type)

            trending_choice = Requests.Trending_Call(
                global_url, url_trend, media_type, time_window, key_word, api_key
            )

            popular_path = Requests.Popular_Call(
                global_url, media_type, url_popular, key_word, api_key
            )

            trend_call = Requests.Request(trending_choice)
            pop_call = Requests.Request(popular_path)

            trend_saved = trend_call.request_to_json()
            pop_saved = pop_call.request_to_json()

            # get_trending.context = trend_saved
            # get_popular.context = pop_saved

            # save trend json clicked
            #TODO: if movie view selected(open json originals) 
            with open(choice_clicked+'_Trending.json', 'w') as w:
                json.dump(trend_saved, w, indent=4,
                          cls=serialize.RequestEncoder)

            # json popular clicked
            with open(choice_clicked + '_Popular.json', 'w') as w:
                json.dump(pop_saved, w, indent=4, cls=serialize.RequestEncoder)


            # if return omitted will raise an error
            return jsonify({
                "Status": 'OK',
                'choice_clicked': choice_clicked,
                'get_trends': trend_saved,
                'get_pops': pop_saved
            })

    # Default view
    else:
    
        #Defaul is movie (view)
        media_type = 'movie/'
        # print('data got  : ', media_type)
        trending_path = Requests.Trending_Call(
            global_url, url_trend, media_type,
            time_window, key_word, api_key
        )

        pop_path = Requests.Popular_Call(
            global_url, media_type, url_popular,
            key_word, api_key
        )

        # print('trending_path : ', trending_path)
        trend_request = Requests.Request(trending_path)
        pop_request = Requests.Request(pop_path)

        trend_jsn = trend_request.request_to_json()
        pop_jsn = pop_request.request_to_json()

        # function Attribute
        get_trending.access_trends = trend_jsn
               
        with open('Trending_original.json', 'w') as w:
            json.dump(trend_jsn, w, indent=4,
                      cls=serialize.RequestEncoder)

        with open('Popular_original.json', 'w') as save_dt:
            json.dump(pop_jsn, save_dt, indent=4, cls=serialize.RequestEncoder)


        # #FIXME get 3 trending data
        # get_trending.get_dt = trend_jsn['results'][5]['backdrop_path']

        return render_template("movies/trending_view.html",
            trends=trend_jsn,
            populars=pop_jsn,
            
        )



# render the most popular movies max(20) in card section

# @Moviesio.context_processor
# def get_popular():

#     pop_choice = 'movie/'
#     popular_path = Requests.Popular_Call(
#         global_url, pop_choice, url_popular, key_word, api_key
#     )
#     popular_list = Requests.Request(popular_path)

#     pop_to_json = popular_list.request_to_json()

#     # create fun attribut
#     get_popular.pop_dt = pop_to_json

#     # save to a local file
#     cls=serialize.RequestEncoder)

#     return dict(
#         popular_movies=get_popular.pop_dt)
#     #     # trend_dt=get_trending.trend_data,
#     #     # data_slide=get_trending.data_slide
#     # )


@Moviesio.context_processor
def get_genres():

    genre_base = 'genre/movie/list'
    genres_url = (global_url + genre_base + key_word + api_key)
    genre_req = Requests.Request(genres_url)

    genre_fetched = genre_req.request_to_json()
        # dump_gnr = json.dumps(genre_to_json, indent=4)

    # # save to jsn file
    # with open('genres.json', 'w') as gnrs:
    #     json.dump(genre_fetched, gnrs, indent=4, sort_keys=True)
    # create Function attribute to access outside of this fun
    get_genres.categ_fetched = genre_fetched

    return dict(
        categories=genre_fetched
    )


# Fetch by categorie

@ Moviesio.route('/catg/<int:genre_id>/<string:genre_name>')
def get_by_category(genre_id, genre_name):

    # Visit tmdb api page to discover more of these options
    movie_discover = 'discover/movie'
    sort_by = 'popularity.desc'
    include_adult = 'true'
    include_video = 'true'
    genre_clicked = genre_id  # (user clicks genre btn)
    print('flask genre clicked : ', genre_clicked)

    discover_url = global_url + movie_discover + key_word + api_key + language+'&sort_by='+sort_by + \
        '&include_adult='+include_adult+'&include_video=' + \
        include_video+'&with_genres='+str(genre_clicked)

    discover_call = Requests.Request(discover_url)
    discover_to_jsn = discover_call.request_to_json()

    # might give(200)response even if you missparsed url (strings)
    #test status code

    for get_name in get_genres.categ_fetched['genres']:
        if genre_clicked == get_name['id']:
            id_name = get_name['name']

    genre_id_name = id_name
    # with open(genre_id_name+'.json', 'w') as new_list:
    #     json.dump(discover_to_jsn, new_list, indent=4)
        
    print('you have clicked Genre id Nm %d and it\'s name is %s :' % (genre_clicked, genre_id_name),
          '\n --> .json file is saved')

    if discover_to_jsn:
        return render_template(
            'movies/trending_view.html',
            genre_results=discover_to_jsn,
            genre_clicked=genre_clicked,
            trends=get_trending.access_trends,

        )
        # return jsonify({
        #     'status : ': 'OK',
        #     'genre_clicked': discover_to_jsn,
        #     'with_genres': genre_clicked
        # })
    else:
        return jsonify('error occured : ', discover_to_jsn.error)


@Moviesio.route('/fetch', methods=['POST', 'GET'])
def search_by():
    if request.method == 'POST':
        # return none if key not found
        query_str = request.form.get('query_search', None)  # input from ajax

        if len(query_str) > 0:
            print('data recieved was : ', query_str)

            query_word = '&query='
            search_word = 'search/movie/'
            search_url = str(global_url + search_word + key_word +
                             api_key + language + query_word + query_str)
            search_call = Requests.Request(search_url)
            search_dt = search_call.request_to_json()

            if len(search_dt['results']) > 1:

                print('Found movie results for %s ' % query_str, '\n',
                      'Global results are %d \n' % len(search_dt['results']))

                with open(query_str + '.json', 'w') as search_res:
                    json.dump(search_dt, search_res, indent=4, sort_keys=True)

                #delete :  (optional)
                for get_dt in search_dt['results']:
                    titles = get_dt['title']
                    if titles:
                        print('--', json.dumps(titles, indent=4))

                    else:
                        Exception()

                return jsonify({
                    'query_search':  search_dt,
                    'query_str': query_str
                })

            else:
                return jsonify({'error': 'Missing data!',
                                },
                               print('could not find search for -->  %s' %
                                     query_str)
                               )
        else:

            return render_template(
                'movies/testme.html',
                query_search=search_dt,
            )

    return render_template(
        'movies/testme.html',
    )

@Moviesio.route('/Popular/movie_detail/')
def movie_detail():
    get_id = route_to_detail.access_id
    append_to = '&append_to_response='

    # Append to url other details
    credit = 'credits'
    images = 'images'
    videos = 'videos'
    # later append other items in detail to url

    movie_url = str(global_url + 'movie/' + get_id + key_word + api_key +
                    language + append_to + credit + ',' + images + ',' + videos)
    url_req = requests.get(movie_url)
    movie_js = url_req.json()

    print('response from server ', url_req.status_code)

    with open('movie_details.json', 'w') as w:
        json.dump(movie_js, w, indent=4)

Project/Moviesio/templates/movies/base_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "movies/head.html" %}
  </head>

  <body>
    <!-- extending Trending view -->
    <section id="home">
      {% block trending %} {% endblock trending %}
    </section>

    <!--extend popular_view  -->
    <section id="movie-card">
      {% block popular %} {% endblock popular %}
    </section>

    <!--Load your extarnal js scripts first to prevent 
    errors  -->
    <!--  jquery/ajax cdn -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script
      src="https://code.jquery.com/jquery-3.5.0.min.js"
      integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/home_switch_view.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/search_results.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/scrolling.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/carousel_slides.js') }}"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/accurate_detail_view.js') }}"
    ></script>
    <!-- 
    <script
      type="text/javascript"
      src="{{ url_for('static', filename = 'js/tv_switch_episodes.js') }}"
    ></script> -->
  </body>
</html>

Project/Moviesio/templates/movies/detail.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% include "movies/head.html" %}

</head>

<body>
    <!-- Redirect to home -->
    <nav class="home mb-20 mt-12 text-center">
        <a href="{{ url_for('movies.main') }}" class="">
            <i class="fas fa-home text-3xl text-black"></i>
        </a>
    </nav>

    <!-- movie dunamique image -->
    <div class="d_container pb-24">

        <img class="" src="https://image.tmdb.org/t/p/original{{ mv_detail['backdrop_path'] }}" alt="movie dynamique">
        <div class="d_caption">
            <div class="d_rating">
                <h1> {{mv_detail['vote_average']}} </h1>
                <i class="fas fa-star-half-alt"></i>
                <i class="fas fa-star-half-alt"></i>
                <i class="fas fa-star-half-alt"></i>
                <i class="fas fa-star-half-alt"></i>
            </div>

            <h5> Runtime : {{mv_detail['runtime']}} min</h5>
            <div class="container ">
                <h2> {{mv_detail['title']}} </h2>
                <p class="text-xl break-words">
                    {{mv_detail['tagline']}}
                </p>
            </div>
            <!-- Trailer button need to play in home  (in site # Youtube) -->
            <a href="https://www.youtube.com/watch?v={{ mv_detail['videos'].results[0]['key'] }}">
                <button class="bg-red-500 text-2xl pr-0 hover:bg-black text-white py-2 px-4 rounded-full mx-32 pr-10">
                    <i class="fas fa-play pl-3 pr-3"></i>
                    Watch trailer
                </button>
            </a>
            <i class="fas fa-pause text-2xl"></i>

        </div>
    </div>

    <section id="detail">
        <div class="grid-container text-white mx-56">
            <div class="row-1 text-black">
                <div class="movie_detail text-xl">
                    <h2 class="m_detail my-10 font-bold text-xl text-black">
                        Details
                    </h2>
                    <p> Country <span class="px-10">
                            {% for production in mv_detail.production_countries %}
                            {% if production %}
                            <span>
                                /
                                {{production['iso_3166_1']}}
                            </span>
                            {% endif %}
                            {% endfor %}
                        </span></p>
                    <hr>
                    <p> Languge <span class="px-10">
                            {% for lang in mv_detail.spoken_languages %}
                            {{ lang['name'] }}
                            {% endfor %}
                        </span></p>
                    <hr>

                    <p> Releaes date <span class="px-10">
                            {{mv_detail['release_date']}}
                        </span></p>
                    <hr>
                </div>
            </div>

            <!-- Story timeline -->
            <div class="row-2">
                <div class="m_story">
                    <h2 class="p_story my-10 font-bold text-xl text-black"> Story Line </h2>
                    <p class="paragraphe text-black">
                        {{mv_detail['overview']}}
                    </p>

                    <p class="pt-4">
                        <span class="categ text-black"> Category : <span class="pl-4 text-red-400">
                                {% for genre in mv_detail.genres %}
                                {% if genre %}
                                <mute> - </mute>
                                {{ genre['name']}}
                                {% endif %}
                                {% endfor %}
                            </span></span>
                    </p>
                </div>

            </div>

            <!-- casts  / movie-trailer  -->
            <div class="casts my-0">
                <div class="row3 text-black">
                    <h2 class="heros text-xl my-0 mb-5 py-0 text-black">
                        Casts
                    </h2>
                    <!-- Control imgs sizes -->
                    {% for casts in mv_detail['credits'].cast %}
                    {% if casts['profile_path'] != null %}
                    <img class="hero" src="https://image.tmdb.org/t/p/w92{{ casts['profile_path'] }}"
                        style="border-radius: 30%;" alt="">
                    <span>
                        {% for cast_name in casts['name'] %}
                        {{cast_name}}
                        {% endfor  %}
                    </span>
                    {%endif%}

                    {% endfor %}
                </div>

            </div>
            <div class="trailer my-20">
                <img src="{{ url_for('static', filename='images/img_movie.jpg')}}" alt="">

            </div>

            <!-- Movie name/paly button -->
            <div class="play row-4 my-32 text-black">
                <h1 class="movie_name text-3xl">
                    <p>{{mv_detail['title']}}</p>
                </h1>
                <button class="bg-red-500 hover:bg-black text-white font-bold py-2 px-4 rounded-full mx-32 pr-10">
                    <i class="fas fa-play pl-3 pr-3"></i>
                    Play
                </button>
            </div>
            <!-- Gallery images -->
            <div class="gallery">

                <img src="{{ url_for ('static', filename = 'images/gallery.png') }}" alt="">
                <img src="{{ url_for ('static', filename = 'images/gallery.png') }}" alt="">
                <img src="{{ url_for ('static', filename = 'images/gallery.png') }}" alt="">
                <img src="{{ url_for ('static', filename = 'images/gallery.png') }}" alt="">
                <img src="{{ url_for ('static', filename = 'images/gallery.png') }}" alt="">
            </div>

            <!-- social -->
            <div class="social text-2xl ml-16">
                <h3 class="my-14 mb-4"> Social </h3>
                <li>
                    <i class="fab fa-github text-3xl"></i>
                </li>
                <li>
                    <i class="fab fa-github text-3xl"></i>
                </li>
                <li>
                    <i class="fab fa-github text-3xl"></i>
                </li>
            </div>
        </div>



    </section>




</body>

</html>

Project/Moviesio/templates/movies/head.html
<!-- Essentiels -->

<title>
  {% block title %} {% endblock title %}
</title>

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!-- Loading all files that changes often (.css/.js) 
    to avoid hard refresh-->

<!-- Css file import -- for movie -->
<link
  rel="stylesheet"
  href="{{ url_for('static', filename = 'css/movie_styling.css')}}"
/>

<!-- Css file import -- for tv 
<link
  rel="stylesheet"
  href="{{ url_for('static', filename = 'css/tv_styling.css')}}"
/>
-->

<!-- spinner css 
<link rel="stylesheet" href="{{ url_for('static', filename = 'css/spinner_css.css')}}">
-->

<!-- bootstrap cdn  -->
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
  crossorigin="anonymous"
/>

<!-- Fonts icons -->
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
/>

<!-- Tailwind css  -->
<link
  href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css"
  rel="stylesheet"
/>

Project/Moviesio/templates/movies/movie_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "movies/head.html" %}
  </head>

  <body>
    <!-- Redirect to home -->
    <nav class="home mb-20 mt-12 text-center">
      <a href="{{ url_for('moviesio.get_trending') }}" class="">
        <i class="fa fa-home text-3xl text-black"></i>
      </a>
    </nav>

    <!-- movie dunamique image -->
    <div class="d_container pb-24">
      <img
        class=""
        src="https://image.tmdb.org/t/p/original{{ mv_detail['backdrop_path'] }}"
        alt="movie dynamique"
      />
      <div class="d_caption">
        <div class="d_rating">
          <h1>{{mv_detail['vote_average']}}</h1>
          <i class="fas fa-star-half-alt"></i>
          <i class="fas fa-star-half-alt"></i>
          <i class="fas fa-star-half-alt"></i>
          <i class="fas fa-star-half-alt"></i>
        </div>

        <h5>Runtime : {{mv_detail['runtime']}} min</h5>
        <div class="container">
          <h2>{{mv_detail['title']}}</h2>
          <p class="text-xl break-words">
            {{mv_detail['tagline']}}
          </p>
        </div>
        <!-- Trailer button need to play in home  (in site # Youtube) -->
        <a
          href="https://www.youtube.com/watch?v={{ mv_detail['videos'].results[0]['key'] }}"
        >
          <button
            class="bg-red-500 text-2xl pr-0 hover:bg-black text-white py-2 px-4 rounded-full mx-32 pr-10"
          >
            <i class="fa fa-play pl-3 pr-3"></i>
            Watch trailer
          </button>
        </a>
        <i class="fas fa-pause text-2xl"></i>
      </div>
    </div>

    <section id="detail">
      <div class="grid-container text-white mx-56">
        <div class="row-1 text-black">
          <div class="movie_detail text-xl">
            <h2 class="m_detail my-10 font-bold text-xl text-black">
              Details
            </h2>
            <p>
              Country
              <span class="px-10">
                {% for production in mv_detail.production_countries %} {% if
                production %}
                <span>
                  / {{production['iso_3166_1']}}
                </span>
                {% endif %} {% endfor %}
              </span>
            </p>
            <hr />
            <p>
              Languge
              <span class="px-10">
                {% for lang in mv_detail.spoken_languages %} {{ lang['name'] }}
                {% endfor %}
              </span>
            </p>
            <hr />

            <p>
              Releaes date
              <span class="px-10">
                {{mv_detail['release_date']}}
              </span>
            </p>
            <hr />
          </div>
        </div>

        <!-- Story timeline -->
        <div class="row-2">
          <div class="m_story">
            <h2 class="p_story my-10 font-bold text-xl text-black">
              Story Line
            </h2>
            <p class="paragraphe text-black">
              {{mv_detail['overview']}}
            </p>

            <p class="pt-4">
              <span class="categ text-black">
                Category :
                <span class="pl-4 text-red-400">
                  {% for genre in mv_detail.genres %} {% if genre %}
                  <mute> - </mute>
                  {{ genre['name']}} {% endif %} {% endfor %}
                </span></span
              >
            </p>
          </div>
        </div>

        <!-- casts  / movie-trailer  -->
        <div class="casts my-0">
          <div class="row3 text-black">
            <h2 class="heros text-xl my-0 mb-5 py-0 text-black">
              Casts
            </h2>
            <!-- Control imgs sizes -->
            {% for casts in mv_detail['credits'].cast %} {% if
            casts['profile_path'] != null %}
            <img
              class="hero"
              src="https://image.tmdb.org/t/p/w92{{ casts['profile_path'] }}"
              style="border-radius: 30%;"
              alt=""
            />
            <span>
              {% for cast_name in casts['name'] %} {{cast_name}} {% endfor %}
            </span>
            {%endif%} {% endfor %}
          </div>
        </div>
        <div class="trailer my-20">
          <img
            src="{{ url_for('static', filename='images/img_movie.jpg')}}"
            alt=""
          />
        </div>

        <!-- Movie name/paly button -->
        <div class="play row-4 my-32 text-black">
          <h1 class="movie_name text-3xl">
            <p>{{mv_detail['title']}}</p>
          </h1>
          <button
            class="bg-red-500 hover:bg-black text-white font-bold py-2 px-4 rounded-full mx-auto pr-10"
          >
            <i class="fa fa-play pl-3 pr-3"></i>
            Play
          </button>
        </div>
        <!-- Gallery images -->
        <div class="gallery">
          <img
            src="{{ url_for ('static', filename = 'images/gallery.png') }}"
            alt=""
          />
          <img
            src="{{ url_for ('static', filename = 'images/gallery.png') }}"
            alt=""
          />
          <img
            src="{{ url_for ('static', filename = 'images/gallery.png') }}"
            alt=""
          />
          <img
            src="{{ url_for ('static', filename = 'images/gallery.png') }}"
            alt=""
          />
          <img
            src="{{ url_for ('static', filename = 'images/gallery.png') }}"
            alt=""
          />
        </div>

        <!-- social -->
        <div class="social text-2xl ml-16">
          <h3 class="my-14 mb-4">Social</h3>
          <li>
            <i class="fa fa-github text-3xl"></i>
          </li>
          <li>
            <i class="fa fa-github text-3xl"></i>
          </li>
          <li>
            <i class="fa fa-github text-3xl"></i>
          </li>
        </div>
      </div>
    </section>
  </body>
</html>

Project/Moviesio/templates/movies/popular_view.html
{% extends "movies/base_view.html" %}

{% block popular %}
<div class="text-center pt-3">
  <h2 class="uppercases">Other Movies - sort by category or search by name</h2>
</div>

<div class="relative text-center">
  <div class="search">

    <form action="/fetch" method="POST">
      <i class="fa fa-search pl-20" aria-hidden="true"></i>
      <input type="text" 
      id="key_search"
       value="{{ request.form['key_search'] }}" name="key_search"
        class="bg-white rounded-full w-64 focus:outline-none  
        focus:shadow-outline" 
        placeholder="search">
        <img class="m-auto" id="loading" />
        
    </form>

    <div id="search_output" class="bg-grey-100 rounded w-64 m-auto">
      <!--  data coming from ajax after 5s from typing -->
    </div>

  </div>
</div>

<!-- getting dynamique category from the api   -->
<!--TODO:  Darken  the edge to indicact mouse scroll  -->
<div class="left mt-6">

</div>
<div class="center pb-16 gap-6 mt-6" id="content">
  {% for category in categories.genres %}
  <div class="internal">
    <a href="{{ url_for('moviesio.get_by_category', genre_id=category.id, genre_name=category.name ) }}">
      <button type="button" id="genre_{{ category.id }}" class="bg-red-500 text-white hover:bg-black text-gray-800 font-bold py-2 px-4 rounded-full genre_button
            " value="{{ category.name }}">
        {{ category['name'] }}
      </button>
    </a>
  </div>
  {% endfor %}
</div>
<div class="right mt-6">
</div>

<!-- Cards rendering -->
<div class="container mt-24 pt-24 mx-auto px-2 my-3">
  <div id="cards_switching" class="grid grid-cols-4 gap-16 mb-4">
    <!--  Switch to TV | Movie on post  -->
    <!-- This whole div will be overrided and replaced -->
    {% if genre_clicked %}
    {% for by_genre in genre_results.results %}

    <div class="mt-4">
      <i class="fas fa-star text-black"></i>
      <i class="fas fa-star text-black"></i>
      <i class="fas fa-star text-black"></i>

        <a href="{{ url_for('moviesio.movie_detail', movie_id=by_genre['id'] )}}">
          <img src="https://image.tmdb.org/t/p/original{{by_genre['poster_path'] }}" alt="movie">
        </a>

        <div class="mt-2">
          <h3 href="#" class="m_link text-lg mt-2 ">
            <!~~getting titles ~~>
              {{by_genre['title']}}
          </h3>
          <div class="flex items-center text-gray-700">
            <span> {{by_genre['release_date']}} </span>
            <span> || </span>
            <span>
              <!~~ //FIXME: need to loop throug list of names[genres] not ids ~~>

            </span>
          </div>
        </div>
    </div>
    {% endfor %}

    {% else %}
    {% for popular in populars.results %}
    <div class="mt-4">
      <i class="fas fa-star text-black"></i>
      <i class="fas fa-star text-black"></i>
      <i class="fas fa-star text-black"></i>

      <!-- ajax will handle which detail page to display  
      since we have two two choice (tv|movie) with diffrent template
        -->
      <a>
        <img src="https://image.tmdb.org/t/p/original{{popular['poster_path'] }}" 
        id="{{ popular['id'] }}"
        onclick="getID(this.id)">
      </a>

      <div class="mt-2">
        <h3 href="#" class="m_link text-lg mt-2 ">
          <!--getting titles -->
          {{popular['title']}}
        </h3>
        <div class="flex items-center text-gray-700">
          <span> {{popular['release_date']}} </span>
          <span> || </span>
          <span>
            <!-- //FIXME: need to loop throug list of names[genres] not ids -->
            {% for pop_gnr in categories['genres'] %}
            {% if  pop_gnr['id'] in popular['genre_ids'] %}
            {{  pop_gnr['name'] }}
            {% endif %}
            {% endfor %}
          </span>
        </div>
      </div>


    </div>
    {% endfor %}
    {% endif %}
  </div>

</div>

<!--  <!~~ Load More button  ~~> 
        <div class="wrapper">
          <button class="bg-red-500 text-white mt-5 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-full">
            Load More
            <hr>
          </button> 
        </div> -->
</div>
{% endblock popular %}